spring.jpa.database-platform=com.pxp.SQLite.demo.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:sqlite:memory:myDb?cache=shared
spring.datasource.url=jdbc:sqlite:C:/workspace/sqlite/SQLite.demo/src/main/resources/hussi.db
spring.datasource.driver-class-name=org.sqlite.JDBC

#spring.datasource.username=pxp
#spring.datasource.password=password
#jdbc:sqlite:memory:myDb?cache=shared&user=pxp&password=password
#jdbc:sqlite:memory:myDb?cache=shared&username=pxp&password=password

spring.jpa.show-sql=true